// This file was autogenerated by gulp-closure-deps plugin.
// Please do not edit.
goog.addDependency('../../../../node_modules/momentum.js/src/momentum/Coordinate.js', ['momentum.Coordinate'], [], false);
goog.addDependency('../../../../node_modules/momentum.js/src/momentum/Draggable.js', ['momentum.Draggable'], ['momentum.Coordinate', 'momentum.Handler', 'momentum.HandlerComponent', 'momentum.utils'], false);
goog.addDependency('../../../../node_modules/momentum.js/src/momentum/Handler.js', ['momentum.Handler'], ['momentum.Coordinate', 'momentum.TrackingPoint', 'momentum.utils'], false);
goog.addDependency('../../../../node_modules/momentum.js/src/momentum/HandlerComponent.js', ['momentum.HandlerComponent'], [], false);
goog.addDependency('../../../../node_modules/momentum.js/src/momentum/Rotatable.js', ['momentum.Rotatable'], ['momentum.Handler', 'momentum.HandlerComponent', 'momentum.utils'], false);
goog.addDependency('../../../../node_modules/momentum.js/src/momentum/TrackingPoint.js', ['momentum.TrackingPoint'], ['momentum.Coordinate'], false);
goog.addDependency('../../../../node_modules/momentum.js/src/momentum/index.js', ['momentum'], ['momentum.Draggable', 'momentum.Handler', 'momentum.Rotatable'], false);
goog.addDependency('../../../../node_modules/momentum.js/src/momentum/utils.js', ['momentum.utils'], ['momentum.Coordinate'], false);
goog.addDependency('../../../../node_modules/momentum.js/src/momentumdebug/Configurator.js', ['momentumdebug.Configurator'], ['momentum.Draggable', 'momentum.utils', 'momentumdebug.ScriptLoader'], false);
goog.addDependency('../../../../node_modules/momentum.js/src/momentumdebug/ScriptLoader.js', ['momentumdebug.ScriptLoader'], [], false);
goog.addDependency('../../../../node_modules/momentum.js/src/momentumdebug/index.js', ['momentumdebug'], ['momentum', 'momentumdebug.Configurator'], false);
goog.addDependency('../../../../src/javascript/fluidts.js', ['fluidts'], ['fluidts.rangeslider'], true);
goog.addDependency('../../../../src/javascript/fluidts/rangeslider.js', ['fluidts.rangeslider'], ['fluidts.rangeslider.ElementProvider', 'goog.dom.classlist', 'goog.object', 'momentum.Draggable', 'momentum.utils'], true);
goog.addDependency('../../../../src/javascript/fluidts/rangeslider/ElementProvider.js', ['fluidts.rangeslider.ElementProvider'], ['goog.dom'], true);